### ISSUE TITLE
Undocumented arguement requirements for this extension

### ISSUE THREAD

**Issue by Reinbowsaur** [Ju1-js/discord-webhook#1]
I noticed that this addon started working in terms of sharing the generation url after removing --gradio-debug from the launch parameters.

I had to do this to get another extension working (i also hadd to add --api but this doesnt seem to be required) and then noticed the hooks I had provided the addon in the past suddenly started posting messages sharing the url to my discord server.

I don't see this listed as a requirement for this extension to work but should be on the front page? Maybe this is something that has being giving you issues during development of this extension too?

**Comment by Ju1-js** [comment]
I've mostly been having issues extracting the images from the image galleries. Once I can get the images, the rest should be a breeze. Ex. Posting to a webhook.

Edit: Haha I didn't even know that --api parameter existed, as the URLs still posted to my webhook as I'm using callbacks rather than the api.
